name: dispatch receiver

on: 
  repository_dispatch:
    types:
      - dispatchSEM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      run: |
        echo "repository_dispatch triggered"
